### ISSUE TITLE
AWS Config not created

### ISSUE THREAD

**Issue by damiendurant** [shlomoswidler/awscli#7]
Hi,

I have an issue testing this recipe with kitchen, aws config file isn't created even with [:awscli][:compile_time] set to true of false.

I workaround this solution, forking the recipe, and adding on both ressources (directory and file) : 

      if not node[:awscli][:compile_time]
        action :create
      end

I don't understand why, action by default is create.

**Comment by shlomoswidler** [comment]
Looks good to me. Please create a Pull Request and I'll accept it.

**Comment by damiendurant** [comment]
Done : #8
